---
# tasks file for ansible-python3

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: yes

- name: Install Python 3
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Run get-pip.py
  command: python3 /tmp/get-pip.py

- name: Install pyOpenSSL using pip
  pip:
    name: "pyOpenSSL=={{ pyOpenSSL_python_module_version }}"
    state: latest

- name: Install Docker Python module
  pip:
    name: "docker=={{ docker_python_module_version }}"
    state: present

- name: Install docker-compose Python package
  pip:
    name: "docker-compose=={{ docker_compose_python_module_version }}"
    state: present

- name: Install pymongo Python package
  pip:
    name: "pymongo=={{ pymongo_python_module_version }}"
    state: present
