name: GitHub Actions Ansible Role Deploy
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: galaxy
        uses: buluma/galaxy-action@v1.0.3
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          git_branch: main
